# -*- coding: utf-8 -*-
"""BookRecommendationSystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W40WdR6TSpp44PelOS8fFIGc7cFuZpvY
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import linear_kernel

df = pd.read_csv("/content/book_data.csv")
df.head()

df = df[["book_title", "book_desc", "book_rating_count"]]
df.head()

df = df.sort_values(by="book_rating_count", ascending=False)
top_5 = df.head()

import plotly.express as px
import plotly.graph_objects as go

labels = top_5["book_title"]
values = top_5["book_rating_count"]
colors = ['gold','lightgreen']


fig = go.Figure(data=[go.Pie(labels=labels, values=values)])
fig.update_layout(title_text="Top 5 Rated Books")
fig.update_traces(hoverinfo='label+percent', textinfo='percent', textfont_size=30,
                  marker=dict(colors=colors, line=dict(color='black', width=3)))
fig.show()

df.isnull().sum()

df = df.dropna()

from sklearn.feature_extraction.text import TfidfVectorizer

feature = df["book_desc"].tolist()
tfidf = text.TfidfVectorizer(input=feature, stop_words="english")
tfidf_matrix = tfidf.fit_transform(feature)
similarity = linear_kernel(tfidf_matrix, tfidf_matrix)

indices = pd.Series(df.index,
                    index=df['book_title']).drop_duplicates()

def book_recommendation(title, similarity = similarity):
    index = indices[title]
    similarity_scores = list(enumerate(similarity[index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    similarity_scores = similarity_scores[0:5]
    bookindices = [i[0] for i in similarity_scores]
    return df['book_title'].iloc[bookindices]

print(book_recommendation("Letters to a Secret Lover", similarity))

