# -*- coding: utf-8 -*-
"""YouTube_Downloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NqauK0-0asbhdF8CBBE6H8x5k_524ObL
"""

pip install pytube

from pytube import YouTube

link = input("Enter link- ")
Downloader = input("Press 1 for video and 2 for audio- ")

if Downloader == '1':
  youtube_1 = YouTube(link)
  videos = youtube_1.streams.filter(progressive = True)
  for i ,v in enumerate(videos):
      print(i,v)
  stream = int(input("Select index for video quality- "))
  videos[stream].download()
  print("Successfully downloaded!")

if Downloader == '2':
    youtube_1 = YouTube(link)
    aud = youtube_1.streams.filter(progressive = False, file_extension = 'mp4')
    for i ,v in enumerate(aud):
        print(i,v)
    strm = int(input("Enter index you want to download- "))
    aud[strm].download()
    print("Successfully downloaded!")

